name: Both Job & Step level Low Time out than JOB level time out Apply

on:
  workflow_dispatch:

jobs:
  job-1:
    name: Job and Step Timeout Example
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
       - name: Job Start
         run: echo "Job Started"
         
       - name: Step with timeout and long sleep
         timeout-minutes: 1
         run: sleep 190

       - name: END Step
         run: echo "This step will not be reached if the step timeout is exceeded"