name: OS Test
on:
  workflow_dispatch:

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print OS
        run: echo "Running on Ubuntu"

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Print OS
        run: echo "Running on Windows"
