name: Windows to run only after Ubuntu OS Test
on:
  workflow_dispatch:

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running on Ubuntu"

  windows-job:
    needs: ubuntu-job
    runs-on: windows-latest
    steps:
      - run: echo "Running on Windows"
