name: Validating Workflow Checkout

on:
  workflow_dispatch:

jobs:
  validate-with-checkout:
    runs-on: ubuntu-latest
    name: Validate With Checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: List files after checkout
        run: ls -la

      - name: Show working directory
        run: pwd

      - name: Display file content
        run: cat devops.txt
