name: Branch Based Deployment-feature2


on:
    push:

jobs:
    build:
        runs-on: ubntu-latest
        steps: 
            - run: echo "This is the build job"

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/main'
        steps:
            - run: echo "Deploying to Production Server"